### ISSUE TITLE
Lambda'ify Project

### ISSUE THREAD

**Issue by metaskills** [peterc/engblogs#1]
I'd like to show how this could work on AWS Lambda but what would be successful for you? Would build and crawl be different tasks or would it be one task where crawl rand before build?

**Comment by peterc** [comment]
The reason for them being separate tasks is really because I wanted to play around with the layout and not have to crawl each time to do the re-build from the underlying data ;-) So laziness for not doing it a more complicated way, really.

But in a Lambda-ized world this could still be two tasks with the success of the first triggering the second to avoid duplication of code, I guess? There are only going to be like 96 tasks running each day (if crawling every 30 minutes) so it's not going to be a cost problem.
